//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "public"
 * f1 -> "void"
 * f2 -> Identifier()
 * f3 -> "("
 * f4 -> ")"
 * f5 -> "{"
 * f6 -> ( VarDeclaration() )*
 * f7 -> ( Statement() )*
 * f8 -> "}"
 */
public class regularMethodDeclaration implements Node {
   public NodeToken f0;
   public NodeToken f1;
   public Identifier f2;
   public NodeToken f3;
   public NodeToken f4;
   public NodeToken f5;
   public NodeListOptional f6;
   public NodeListOptional f7;
   public NodeToken f8;

   public regularMethodDeclaration(NodeToken n0, NodeToken n1, Identifier n2, NodeToken n3, NodeToken n4, NodeToken n5, NodeListOptional n6, NodeListOptional n7, NodeToken n8) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
      f6 = n6;
      f7 = n7;
      f8 = n8;
   }

   public regularMethodDeclaration(Identifier n0, NodeListOptional n1, NodeListOptional n2) {
      f0 = new NodeToken("public");
      f1 = new NodeToken("void");
      f2 = n0;
      f3 = new NodeToken("(");
      f4 = new NodeToken(")");
      f5 = new NodeToken("{");
      f6 = n1;
      f7 = n2;
      f8 = new NodeToken("}");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

